mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/common_project?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 101.132.64.241
    password: bda5vGiUhGoAys86
    port: 6379
    jedis:
      pool:
        max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
server:
  port: 9003

